access_key_id: "AKIAJCHMCZ74YIOJUH3Q"
secret_access_key: "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"
key_pair: "APKAIUJ4WNN525JIXWXA"
image_id: ""
instance_type: ""
availability-zone: ""
security_group_ids: ""
